# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_RTS490XA_HUB)		+= rts490xa-hub.o
obj-$(CONFIG_MFD_RTS591X_I2C)		+= rts591x-mfd-i2c.o
obj-$(CONFIG_UAPI_IOMATRIX)		+= uapi-iomatrix.o
obj-$(CONFIG_RTS591X_ESPI_SNOOP)		+= rts591x-espi-snoop.o
