# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_PECI_ASPEED)	+= peci-aspeed.o
obj-$(CONFIG_PECI_NPCM)		+= peci-npcm.o
obj-$(CONFIG_PECI_IOMATRIX)	+= peci-iomatrix.o
obj-$(CONFIG_PECI_RTS591X_OOB)	+= peci-rts591x-oob.o
